config/routes.rb
Rails.application.routes.draw do
  resources :input_forms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  mount GoodJob::Engine => "good_job"

  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/input_form.rb
class InputForm < ApplicationRecord
  validates :title, presence: true, length: {maximum: 255}
  validates :description, allow_blank: true, length: {maximum: 2_000}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/input_forms_controller.rb
class InputFormsController < ApplicationController
  before_action :set_input_form, only: %i[show edit update destroy]

  # GET /input_forms
  def index
    @input_forms = InputForm.all
  end

  # GET /input_forms/1
  def show
  end

  # GET /input_forms/new
  def new
    @input_form = InputForm.new
  end

  # GET /input_forms/1/edit
  def edit
  end

  # POST /input_forms
  def create
    @input_form = InputForm.new(input_form_params)

    if @input_form.save
      redirect_to @input_form, notice: "Input form was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /input_forms/1
  def update
    if @input_form.update(input_form_params)
      redirect_to @input_form, notice: "Input form was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /input_forms/1
  def destroy
    @input_form.destroy
    redirect_to input_forms_url, notice: "Input form was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_input_form
    @input_form = InputForm.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def input_form_params
    params.require(:input_form).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/input_forms/edit.html.erb
<%= render(Primer::Beta::Heading.new(tag: :h1)) { "Editing input form" } %>

<%= primer_form_with(model: @input_form) do |f| %>
  <%= render InputFormForm.new(f) %>
<% end %>

<%= render(Primer::Beta::Button.new(tag: :a, href: input_form_path(@input_form), block: :true, mt: 2)) { "Show this input form" } %>
<%= render(Primer::Beta::Button.new(tag: :a, href: input_forms_path, block: :true, mt: 2)) { "Back to input forms" } %>

app/views/input_forms/index.html.erb
<%= render(Primer::Beta::Heading.new(tag: :h1)) { InputForm.model_name.human } %>

<%= render(Primer::Beta::Flash.new(scheme: :success, mt: 3)) { notice } if notice %>

<div id="input_forms">
  <% @input_forms.each do |input_form| %>
    <%= render Primer::Box.new(bg: :subtle, mt: 3, p: 3, id: dom_id(input_form)) do %>
      <p>
        <strong>Id:</strong>
        <%= input_form.id %>
      </p>
      <p>
        <strong>Title:</strong>
        <%= input_form.title %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= input_form.description %>
      </p>
      <p>
        <strong>Created at:</strong>
        <%= l input_form.created_at %>
      </p>
      <p>
        <strong>Updated at:</strong>
        <%= l input_form.updated_at %>
      </p>
      <%= render(Primer::Beta::Button.new(tag: :a, href: input_form_path(input_form), block: :true)) { "Show this input form" } %>
    <% end %>
  <% end %>
</div>

<%= render(Primer::Beta::Button.new(tag: :a, href: new_input_form_path, block: :true, mt: 3)) { "New input form" } %>

app/views/input_forms/new.html.erb
<%= render(Primer::Beta::Heading.new(tag: :h1)) { 'New input form' } %>

<%= primer_form_with(model: @input_form) do |f| %>
  <%= render InputFormForm.new(f) %>
<% end %>

<%= render(Primer::Beta::Button.new(tag: :a, href: input_forms_path, block: :true, mt: 2)) { "Back to input forms" } %>

app/views/input_forms/show.html.erb
<%= render(Primer::Beta::Flash.new(scheme: :success, mb: 3)) { notice } if notice %>

<%= render Primer::Box.new(bg: :subtle, mt: 3, p: 3, id: dom_id(@input_form)) do %>
  <%= render(Primer::Beta::Heading.new(tag: :h2, mb: 3)) { @input_form.title } %>
  <%= simple_format @input_form.description %>
  <p>
    <strong>Id:</strong>
    <%= @input_form.id %>
  </p>
  <p>
    <strong>Created at:</strong>
    <%= l @input_form.created_at %>
  </p>
  <p>
    <strong>Updated at:</strong>
    <%= l @input_form.updated_at %>
  </p>
<% end %>

<%= render(Primer::Beta::Button.new(tag: :a, href: edit_input_form_path(@input_form), block: :true, mt: 3)) { "Edit this input form" } %>
<%= render(Primer::Beta::Button.new(tag: :a, href: input_forms_path, block: :true, mt: 2)) { "Back to input forms" } %>
<%= render(Primer::Beta::Button.new(tag: :a, href: input_form_path(@input_form), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, scheme: :danger, block: :true, mt: 2)) { "Destroy this input form" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>September</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "primer_view_components", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body style="background: #22272e">
    <div class="container-sm p-5 mt-5 mb-5 rounded" style="background: #fff">
      <%= yield %>
    </div>
  </body>
</html>